
import React,{useMemo,useState} from "react";import {domains,colleges} from "../data/mockData";import {Card,Badge,Icon,Button,Empty} from "../components/UI";
export default function Colleges({go,setCollege}){
 const [domain,setDomain]=useState("Engineering"),[q,setQ]=useState(""),[own,setOwn]=useState("All"),[city,setCity]=useState("All");
 const filtered=useMemo(()=>colleges.filter(c=>(!domain||c.domain===domain)&&(own==="All"||c.ownership===own)&&(city==="All"||c.city===city)&&c.name.toLowerCase().includes(q.toLowerCase())),[domain,q,own,city]);
 const open=c=>{setCollege(c);go("college")};
 return <div className="page"><div className="pageintro"><div><span className="kicker">COLLEGE NAVIGATOR</span><h1>What do you want to study?</h1><p>Explore across domains, then narrow by program, specialization, location and ownership.</p></div></div>
 <div className="domainrail">{domains.map(d=><button key={d.name} className={domain===d.name?"selected":""} onClick={()=>setDomain(d.name)}><span><Icon name={d.icon}/></span><b>{d.name}</b><small>{d.count} colleges</small></button>)}</div>
 <div className="collegehead"><div><span className="kicker">{domain?.toUpperCase()}</span><h2>{domain} colleges</h2></div><div className="countstats"><span><b>{domain==="Engineering"?480:domains.find(d=>d.name===domain)?.count}</b>Total</span><span><b>{domain==="Engineering"?35:"—"}</b>Government</span><span><b>{domain==="Engineering"?20:"—"}</b>Govt. Aided</span><span><b>{domain==="Engineering"?425:"—"}</b>Private</span></div></div>
 <div className="exploregrid"><aside className="filters"><div className="filtertitle"><Icon name="SlidersHorizontal"/><b>Filters</b><button onClick={()=>{setOwn("All");setCity("All");setQ("")}}>Reset</button></div><label>Ownership<select value={own} onChange={e=>setOwn(e.target.value)}><option>All</option><option>Government</option><option>Government Aided</option><option>Private</option></select></label><label>Program<select><option>All programs</option><option>B.E./B.Tech</option><option>MBBS</option><option>B.Com</option></select></label><label>Specialization<select><option>All specializations</option><option>ECE</option><option>CSE</option><option>Mechanical</option></select></label><label>City<select value={city} onChange={e=>setCity(e.target.value)}><option>All</option>{[...new Set(colleges.map(c=>c.city))].map(x=><option key={x}>{x}</option>)}</select></label><label>Fee range<input type="range"/></label></aside>
 <section><div className="resultbar"><div className="searchinput"><Icon name="Search"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search colleges..."/></div><select><option>Recommended</option><option>Name A–Z</option><option>Fees</option></select></div><p className="resultcount">{filtered.length} demo records match your current filters</p><div className="collegecards">{filtered.length?filtered.map(c=><Card key={c.id} className="collegecard"><div className="collegevisual"><Icon name="Landmark" size={34}/><Badge>{c.ownership}</Badge></div><div className="collegeinfo"><div className="rowtop"><div><h3>{c.name}</h3><p><Icon name="MapPin" size={14}/>{c.city}, {c.state}</p></div><button className="iconbtn"><Icon name="Bookmark"/></button></div><div className="tags">{c.specializations.slice(0,3).map(x=><span key={x}>{x}</span>)}</div><div className="collegefacts"><span><small>PROGRAM</small><b>{c.program}</b></span><span><small>ADMISSION</small><b>{c.admission}</b></span><span><small>FEES</small><b>{c.fees}</b></span><span><small>ACCREDITATION</small><b>{c.accreditation}</b></span></div><div className="cardactions"><Button onClick={()=>open(c)}>View college</Button><Button variant="secondary" onClick={()=>go("compare")}><Icon name="GitCompareArrows" size={16}/> Compare</Button></div></div></Card>):<Empty/>}</div></section></div>
 </div>
}
