
import React from "react";import {Stat,Card,Badge,Icon,Button} from "../components/UI";import {scholarships,opportunities,events} from "../data/mockData";
export default function Dashboard({go}){
 const name=localStorage.getItem("cc_user")||"Arjun";
 return <div className="page"><div className="pageintro"><div><span className="kicker">FRIDAY, 24 JULY</span><h1>Good evening, {name}.</h1><p>Here are the things worth your attention right now.</p></div><Button onClick={()=>go("assistant")}><Icon name="Sparkles" size={17}/> Ask Compass</Button></div>
 <div className="stats"><Stat icon="Award" value="6" title="Scholarship matches" sub="2 closing soon"/><Stat icon="BriefcaseBusiness" value="12" title="Career opportunities" sub="5 new this week"/><Stat icon="CalendarDays" value="4" title="Upcoming events" sub="Next: 12 Aug"/><Stat icon="Bookmark" value="8" title="Saved items" sub="Across 4 categories"/></div>
 <div className="dashgrid"><section><div className="sectiontitle"><div><span>RECOMMENDED</span><h2>Picked for your profile</h2></div><button onClick={()=>go("career")}>View all <Icon name="ArrowRight" size={15}/></button></div>{opportunities.slice(0,2).map(o=><Card className="rowcard" key={o.id}><span className="roundicon"><Icon name={o.type==="Hackathon"?"Trophy":"BriefcaseBusiness"}/></span><div className="grow"><div className="rowtop"><Badge>{o.type}</Badge><small>{o.match}% match</small></div><h3>{o.title}</h3><p>{o.org} · {o.location}</p><div className="meta"><span><Icon name="Clock3" size={14}/>{o.days} days left</span><span>{o.skills.join(" · ")}</span></div></div><button className="iconbtn"><Icon name="Bookmark"/></button></Card>)}</section>
 <aside><div className="sectiontitle"><div><span>DEADLINES</span><h2>Coming up</h2></div></div><Card className="deadline">{scholarships.slice(0,2).map(s=><div key={s.id}><span className="datebox"><b>{s.days}</b><small>DAYS</small></span><div><h4>{s.name}</h4><p>{s.provider}</p></div></div>)}</Card><div className="sectiontitle second"><div><span>EVENTS</span><h2>Near you</h2></div></div><Card className="deadline">{events.slice(0,2).map(e=><div key={e.id}><span className="roundicon"><Icon name="CalendarDays"/></span><div><h4>{e.title}</h4><p>{e.date} · {e.location}</p></div></div>)}</Card></aside></div>
 </div>
}
