
import React from "react";import {Icon,Button,Card} from "../components/UI";import {domains} from "../data/mockData";
const features=[["GraduationCap","College Navigator","Explore colleges by domain, program, specialization and ownership."],["BookOpen","Academics","Keep semester resources and useful study material organized."],["BriefcaseBusiness","Career Development","Discover internships, hackathons, courses and placement preparation."],["Award","Scholarships","Surface scholarships that fit a student's profile."],["CalendarDays","Events","Find workshops, symposiums, technical events and meetups."],["Users","Student Network","Discover peers for projects, study groups and hackathon teams."],["Sparkles","AI Assistance","Ask Campus Compass questions and receive structured platform results."]];
export default function Landing({go}){
 return <div className="landing">
  <header className="landingnav"><button className="brand" onClick={()=>go("landing")}><span><Icon name="Compass" size={24}/></span><div>Campus<b>Compass</b></div></button><nav><button onClick={()=>go("colleges")}>Explore colleges</button><button onClick={()=>go("scholarships")}>Scholarships</button><button onClick={()=>go("career")}>Career</button></nav><div><Button variant="ghost" onClick={()=>go("login")}>Log in</Button><Button onClick={()=>go("register")}>Get started</Button></div></header>
  <section className="hero"><div className="eyebrow"><Icon name="Sparkles" size={15}/> Your student journey, connected</div><h1>Navigate your entire<br/><em>college journey.</em></h1><p>Discover colleges, academic resources, career opportunities, scholarships, events and students from one thoughtful platform.</p><div className="heroactions"><Button onClick={()=>go("register")}>Get started <Icon name="ArrowRight" size={17}/></Button><Button variant="secondary" onClick={()=>go("colleges")}>Explore colleges</Button></div><div className="trust"><span><Icon name="CheckCircle2"/>Personalized discovery</span><span><Icon name="CheckCircle2"/>Structured information</span><span><Icon name="CheckCircle2"/>Built for students</span></div></section>
  <section className="preview"><div className="previewbar"><span></span><span></span><span></span><small>campuscompass / dashboard</small></div><div className="previewbody"><div><small>YOUR COMPASS</small><h2>Good evening, Arjun.</h2><p>Here are the things worth your attention today.</p></div><div className="previewstats"><Card><b>6</b><span>Scholarship matches</span></Card><Card><b>12</b><span>Career opportunities</span></Card><Card><b>4</b><span>Upcoming events</span></Card></div></div></section>
  <section className="section"><div className="sectionhead"><span>ONE PLATFORM</span><h2>Everything students keep searching for,<br/>finally in one place.</h2></div><div className="featuregrid">{features.map(f=><Card key={f[1]}><span className="featureicon"><Icon name={f[0]}/></span><h3>{f[1]}</h3><p>{f[2]}</p><button onClick={()=>go(f[1]==="College Navigator"?"colleges":f[1]==="AI Assistance"?"assistant":f[1].toLowerCase().split(" ")[0])}>Explore <Icon name="ArrowUpRight" size={15}/></button></Card>)}</div></section>
  <section className="cta"><div><span>START EXPLORING</span><h2>Your next opportunity shouldn't be hard to find.</h2><p>Create a demo profile and experience Campus Compass.</p></div><Button onClick={()=>go("register")}>Create your profile <Icon name="ArrowRight" size={17}/></Button></section>
  <footer><div className="brand"><span><Icon name="Compass"/></span><div>Campus<b>Compass</b></div></div><p>Frontend prototype · Mock data only</p></footer>
 </div>
}
