
import React,{useState} from "react";import {Button,Icon,Card} from "../components/UI";
export default function Onboarding({go}){
 const [step,setStep]=useState(1); const [role,setRole]=useState("College Student");
 const roles=[["School Student","School","I'm exploring colleges and programs."],["College Student","GraduationCap","I'm studying and building my career."],["Graduate","BriefcaseBusiness","I'm exploring career opportunities."]];
 return <div className="onboard"><div className="onhead"><div className="brand"><span><Icon name="Compass"/></span><div>Campus<b>Compass</b></div></div><small>Step {step} of 3</small></div><div className="progress"><i style={{width:`${step*33.33}%`}}/></div><div className="onbody">
 {step===1&&<><span className="kicker">LET'S PERSONALIZE YOUR COMPASS</span><h1>What best describes you?</h1><p>We'll shape the experience around where you are right now.</p><div className="rolegrid">{roles.map(r=><Card key={r[0]} className={role===r[0]?"selected":""}><button onClick={()=>setRole(r[0])}><span><Icon name={r[1]}/></span><h3>{r[0]}</h3><p>{r[2]}</p><Icon name={role===r[0]?"CheckCircle2":"Circle"} /></button></Card>)}</div></>}
 {step===2&&<><span className="kicker">YOUR EDUCATION</span><h1>Tell us what you're studying.</h1><p>This powers academics and opportunity matching.</p><div className="formgrid"><label>College<input defaultValue="Government College of Engineering"/></label><label>Degree<select><option>B.E.</option><option>B.Tech</option><option>B.Sc</option></select></label><label>Program / Department<select><option>Electronics & Communication Engineering</option><option>Computer Science</option></select></label><label>Year<select><option>2nd Year</option><option>1st Year</option><option>3rd Year</option></select></label><label>State<input defaultValue="Tamil Nadu"/></label><label>District<input defaultValue="Tirunelveli"/></label></div></>}
 {step===3&&<><span className="kicker">YOUR INTERESTS</span><h1>What are you building toward?</h1><p>Choose a few. You can change these later.</p><div className="chips">{["Web Development","IoT","Software Engineering","Hackathons","Embedded Systems","Startups","UI/UX","Cloud","Higher Studies"].map((x,i)=><button className={i<4?"chosen":""} key={x}>{x}</button>)}</div><label className="wide">Skills<input defaultValue="Python, C++, React, Arduino" /></label></>}
 <div className="onactions">{step>1?<Button variant="secondary" onClick={()=>setStep(step-1)}>Back</Button>:<span/>}<Button onClick={()=>step<3?setStep(step+1):go("dashboard")}>{step<3?"Continue":"Open my dashboard"} <Icon name="ArrowRight" size={17}/></Button></div>
 </div></div>
}
